# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240321-084414-spry-prism

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru


pipeline:
  - name: SpacyNLP
    model: "ru_core_news_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: SpacyEntityExtractor
    dimensions: ["PERSON", "LOC", "ORG", "PRODUCT"]
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    dimensions: [ "time", "number", "amount-of-money" ]
    locale: "ru_GB"
    timezone: "Asia/Bishkek"
    timeout: 3
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: true
  - name: "FallbackClassifier"
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "UnexpecTEDIntentPolicy"
    max_history: 5
    epochs: 100
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
    constrain_similarities: true